# Generated by Django 4.1.4 on 2023-01-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('credit', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.TextField()),
                ('recommand', models.DecimalField(decimal_places=0, max_digits=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='search.course')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradindpolicy', models.TextField()),
                ('classMethod', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='search.course')),
            ],
        ),
    ]
