# Generated by Django 4.1.4 on 2023-01-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradindpolicy', models.TextField()),
                ('classMethod', models.TextField()),
                ('resp', models.TextField()),
                ('recommand', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 'Response',
            },
        ),
        migrations.RemoveField(
            model_name='experience',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('courseName', 'professor', 'semester')},
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='response',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='search.course'),
        ),
    ]
